export const SET_SUCCESS = "SET_SUCCESS";
export const GET_REQUESTS = "GET_REQUESTS";
export const GET_REQUESTS_ERROR = "GET_REQUESTS_ERROR";
export const SET_FORGOT_LOADING = "SET_FORGOT_LOADING";
export const SET_FORGOT_FAIL = "SET_FORGOT_FAIL";
export const SET_FORGOT_SUCCESS = "SET_FORGOT_SUCCESS";
export const SET_RESET_INVALID = "SET_RESET_INVALID";
export const SET_RESET_FAIL = "SET_RESET_ERROR";
export const SET_RESET_SUCCESS = "SET_RESET_SUCCESS";
export const SET_RESET_LOADING = "SET_RESET_LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";