export const SET_SUCCESS = "SET_SUCCESS";
export const GET_REQUESTS = "GET_REQUESTS";
export const GET_REQUESTS_ERROR = "GET_REQUESTS_ERROR";
export const SET_FORGOT_LOADING = "SET_FORGOT_LOADING";
export const SET_FORGOT_FAIL = "SET_FORGOT_FAIL";
export const SET_FORGOT_SUCCESS = "SET_FORGOT_SUCCESS";
export const SET_RESET_INVALID = "SET_RESET_INVALID";
export const SET_RESET_FAIL = "SET_RESET_ERROR";
export const SET_RESET_SUCCESS = "SET_RESET_SUCCESS";
export const SET_RESET_LOADING = "SET_RESET_LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const CREATE_EVENT = "CREATE_EVENT";
export const RETRIEVE_EVENTS = "RETRIEVE_EVENTS";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const CREATE_SPEAKER = "CREATE_SPEAKER";
export const RETRIEVE_SPEAKERS = "RETRIEVE_SPEAKERS";
export const UPDATE_SPEAKER = "UPDATE_SPEAKER";
export const DELETE_SPEAKER = "DELETE_SPEAKER";


export const CREATE_BROADCASTPOST = "CREATE_BROADCASTPOST";
export const RETRIEVE_BROADCASTPOSTS = "RETRIEVE_BROADCASTPOSTS";
export const UPDATE_BROADCASTPOST = "UPDATE_BROADCASTPOST";
export const DELETE_BROADCASTPOST = "DELETE_BROADCASTPOST";


export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";


export const CREATE_HOST = "CREATE_HOST";
export const RETRIEVE_HOSTS = "RETRIEVE_HOSTS";
export const UPDATE_HOST = "UPDATE_HOST";
export const DELETE_HOST = "DELETE_HOST";


export const CREATE_DISCUSSION = "CREATE_DISCUSSION";
export const RETRIEVE_DISCUSSIONS = "RETRIEVE_DISCUSSIONS";
export const UPDATE_DISCUSSION = "UPDATE_DISCUSSION";
export const DELETE_DISCUSSION = "DELETE_DISCUSSION";


export const CREATE_GROUP = "CREATE_GROUP";
export const RETRIEVE_GROUPS = "RETRIEVE_GROUPS";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";


export const CREATE_ABOUT = "CREATE_ABOUT";
export const RETRIEVE_ABOUTS = "RETRIEVE_ABOUTS";
export const UPDATE_ABOUT = "UPDATE_ABOUT";
export const DELETE_ABOUT = "DELETE_ABOUT";


export const CREATE_STATS = "CREATE_STATS";
export const RETRIEVE_STATSS = "RETRIEVE_STATSS";
export const UPDATE_STATS = "UPDATE_STATS";
export const DELETE_STATS = "DELETE_STATS";

export const CREATE_WARD = "CREATE_WARD";
export const RETRIEVE_WARDS = "RETRIEVE_WARDS";
export const UPDATE_WARD = "UPDATE_WARD";
export const DELETE_WARD = "DELETE_WARD";


export const CREATE_FEDERAL = "CREATE_FEDERAL";
export const RETRIEVE_FEDERALS = "RETRIEVE_FEDERALS";
export const UPDATE_FEDERAL = "UPDATE_FEDERAL";
export const DELETE_FEDERAL = "DELETE_FEDERAL";


export const CREATE_STATE = "CREATE_STATE";
export const RETRIEVE_STATES = "RETRIEVE_STATES";
export const UPDATE_STATE = "UPDATE_STATE";
export const DELETE_STATE = "DELETE_STATE";


export const CREATE_SENATORIAL = "CREATE_SENATORIAL";
export const RETRIEVE_SENATORIALS = "RETRIEVE_SENATORIALS";
export const UPDATE_SENATORIAL = "UPDATE_SENATORIAL";
export const DELETE_SENATORIAL = "DELETE_SENATORIAL";


export const CREATE_NOMINATIONCATEGORY = "CREATE_NOMINATIONCATEGORY";
export const RETRIEVE_NOMINATIONCATEGORYS = "RETRIEVE_NOMINATIONCATEGORYS";
export const UPDATE_NOMINATIONCATEGORY = "UPDATE_NOMINATIONCATEGORY";
export const DELETE_NOMINATIONCATEGORY = "DELETE_NOMINATIONCATEGORY";


export const CREATE_STATEHOUSE = "CREATE_STATEHOUSE";
export const RETRIEVE_STATEHOUSES = "RETRIEVE_STATEHOUSES";
export const UPDATE_STATEHOUSE = "UPDATE_STATEHOUSE";
export const DELETE_STATEHOUSE = "DELETE_STATEHOUSE";


export const CREATE_LGA = "CREATE_LGA";
export const RETRIEVE_LGAS = "RETRIEVE_LGAS";
export const UPDATE_LGA = "UPDATE_LGA";
export const DELETE_LGA = "DELETE_LGA";


export const CREATE_GATEWAY = "CREATE_GATEWAY";
export const RETRIEVE_GATEWAYS = "RETRIEVE_GATEWAYS";
export const UPDATE_GATEWAY = "UPDATE_GATEWAY";
export const DELETE_GATEWAY = "DELETE_GATEWAY";
export const DELETE_ALL_GATEWAYS = "DELETE_ALL_GATEWAYS";

export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const RETRIEVE_COUNTRIES = "RETRIEVE_COUNTRIES";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";


export const CREATE_BROADCASTTYPE = "CREATE_BROADCASTTYPE";
export const RETRIEVE_BROADCASTTYPES = "RETRIEVE_BROADCASTTYPES";
export const UPDATE_BROADCASTTYPE = "UPDATE_BROADCASTTYPE";
export const DELETE_BROADCASTTYPE = "DELETE_BROADCASTTYPE";


export const CREATE_DISCUSSIONSPACEOWNER = "CREATE_DISCUSSIONSPACEOWNER";
export const RETRIEVE_DISCUSSIONSPACEOWNERS = "RETRIEVE_DISCUSSIONSPACEOWNERS";
export const UPDATE_DISCUSSIONSPACEOWNER = "UPDATE_DISCUSSIONSPACEOWNER";
export const DELETE_DISCUSSIONSPACEOWNER = "DELETE_DISCUSSIONSPACEOWNER";


export const CREATE_ELECTEDPOSITION = "CREATE_ELECTEDPOSITION";
export const RETRIEVE_ELECTEDPOSITIONS = "RETRIEVE_ELECTEDPOSITIONS";
export const UPDATE_ELECTEDPOSITION = "UPDATE_ELECTEDPOSITION";
export const DELETE_ELECTEDPOSITION = "DELETE_ELECTEDPOSITION";


export const CREATE_EVENTHOSTTYPE = "CREATE_EVENTHOSTTYPE";
export const RETRIEVE_EVENTHOSTTYPES = "RETRIEVE_EVENTHOSTTYPES";
export const UPDATE_EVENTHOSTTYPE = "UPDATE_EVENTHOSTTYPE";
export const DELETE_EVENTHOSTTYPE = "DELETE_EVENTHOSTTYPE";


export const CREATE_EVENTCATEGORY = "CREATE_EVENTCATEGORY";
export const RETRIEVE_EVENTCATEGORYS = "RETRIEVE_EVENTCATEGORYS";
export const UPDATE_EVENTCATEGORY = "UPDATE_EVENTCATEGORY";
export const DELETE_EVENTCATEGORY = "DELETE_EVENTCATEGORY";


export const CREATE_NOTIFICATIONTYPES = "CREATE_NOTIFICATIONTYPES";
export const RETRIEVE_NOTIFICATIONTYPES = "RETRIEVE_NOTIFICATIONTYPES";
export const UPDATE_NOTIFICATIONTYPES = "UPDATE_NOTIFICATIONTYPES";
export const DELETE_NOTIFICATIONTYPES = "DELETE_NOTIFICATIONTYPES";


export const CREATE_DONATIONTYPE = "CREATE_DONATIONTYPE";
export const RETRIEVE_DONATIONTYPES = "RETRIEVE_DONATIONTYPES";
export const UPDATE_DONATIONTYPE = "UPDATE_DONATIONTYPE";
export const DELETE_DONATIONTYPE = "DELETE_DONATIONTYPE";


export const CREATE_DONATION = "CREATE_DONATION";
export const RETRIEVE_DONATIONS = "RETRIEVE_DONATIONS";
export const UPDATE_DONATION = "UPDATE_DONATION";
export const DELETE_DONATION = "DELETE_DONATION";


